name: Daily Drive Backup to MegaUp

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Rclone & Dependencies
        run: |
          curl https://rclone.org/install.sh | sudo bash
          pip install -r requirements.txt

      - name: Configure Rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG_DATA }}" > ~/.config/rclone/rclone.conf

      - name: Run Transfer & Cleanup
        env:
          MEGAUP_KEY1: ${{ secrets.MEGAUP_KEY1 }}
          MEGAUP_FOLDER_ID: "63172"
          RCLONE_REMOTE: "ShareDrive" # သင့် rclone.conf ထဲက remote အမည် အတိအကျ
        run: |
          python transfer.py
